export const TERMS_VERSION = '2026-09-v1';
export const PRIVACY_VERSION = '2026-09-v1';

export type LegalDocument = {
  title: string;
  version: string;
  paragraphs: readonly string[];
};

export const TERMS_TITLE = 'Terms and Conditions';
export const PRIVACY_TITLE = 'Privacy Policy';

export const TERMS_PARAGRAPHS: readonly string[] = [
  'About SkillMatch. SkillMatch is a livelihood matching and skills platform for the Barangay Santa Ana, Pateros project. It helps local Workers and Clients find and book work. You use SkillMatch through the SkillMatch mobile application. The SkillMatch website is an information page only. It is not the operational Worker, Client, or Administrator app.',
  'Acceptance of these Terms. By creating an account and agreeing to these Terms, you agree to use SkillMatch according to this document and the Privacy Policy. SkillMatch records the version you accepted on your account. If SkillMatch publishes a new version, you may need to review and accept it before you can continue. These Terms describe how the current SkillMatch system works. They are project terms for this capstone platform. They are not a guarantee of work, income, or a particular booking outcome.',
  'Accounts and roles. SkillMatch has three operational roles: Worker, Client, and Administrator. You may register as a Worker or as a Client. Administrator accounts are created only through authorized project/administration paths. You are responsible for the information you submit and for keeping your sign-in details confidential. SkillMatch may restrict or deactivate an account when needed for safety, abuse handling, or platform administration. A deactivated account cannot use the operational app.',
  "Worker verification. If you register as a Worker and you are not already verified, you must submit a valid-ID image before you can use the Worker app. Supported ID types are PhilSys National ID / ePhilID, LTO Driver's License, Philippine Passport, UMID, and Postal ID. An Administrator reviews the submission and may approve or reject it. SkillMatch does not check your ID against a government database and does not promise that a submission will be approved. A verified Worker may be included in job matching. An unverified Worker is not included. Workers who were already verified before this identity-submission process remain verified unless later restricted.",
  'Job postings and opportunities. A Client may post a job for work inside Barangay Santa Ana, Pateros. The job pin must fall inside the supported service area. The Client chooses a primary skill and may add other required skills, a description, schedule, budget, payment method, and a written address. SkillMatch stores a job title based on the primary skill. Eligible Workers can see matching opportunities. Seeing an opportunity does not mean the job is reserved for that Worker.',
  'How a Worker is chosen. SkillMatch does not assign a Worker automatically. A Client does not pick a Worker from a ranked list. AI does not choose the Worker. The flow is: a Client posts a job; SkillMatch determines which Workers are eligible and may rank opportunities to help display them; an eligible Worker may accept; the first valid eligible Worker acceptance wins and creates a confirmed booking.',
  'Bookings. After acceptance, both parties see a confirmed booking. Only the Client may mark a booking completed after the work is done. Either the Client or the Worker may cancel while cancellation is still allowed. SkillMatch does not automatically find a replacement Worker after cancellation. SkillMatch does not provide dispute arbitration, refunds, or compensation beyond what the current app actually does.',
  'User conduct. You agree to provide truthful information, treat other users respectfully, and use SkillMatch only for legitimate livelihood matching in the supported service area. You must not impersonate others, submit false identity documents, harass users, manipulate bookings or payments, or try to bypass access controls. Users may submit reports. Administrators may review reports. SkillMatch may restrict accounts based on that review or other administrative need.',
  "Messages and content. Chat is available only for a confirmed booking between that Client and that Worker. You may send messages only while the booking is confirmed. Chat is not a general messaging app. Do not share information you are not willing to send to the other party on that booking. Users are responsible for the information and content they submit through SkillMatch. Administrators may review reports and may restrict or deactivate accounts when appropriate under the platform's administrative controls.",
  'Payments. SkillMatch currently presents two methods: Cash and QR Ph. Cash is arranged between the Client and Worker; the Worker confirms in the app that cash was received. QR Ph is shown through PayMongo in TEST mode for demonstration. It is not a live production payment service and is not real-money settlement. Do not scan a SkillMatch test QR with GCash, Maya, a banking app, or any real payer. SkillMatch is not a licensed payments provider and does not hold your money.',
  "AI-assisted features. Matching and hiring decisions are not made by AI. Help/FAQ answers come from a local SkillMatch knowledge base and do not look up your private account, booking, or payment records. Resume Builder fills a fixed template from information already on a Worker profile; it does not invent work history. Skill Gap compares required job skills with a Worker's saved skills and may offer optional AI guidance text. AI-assisted text is not guaranteed to be correct.",
  'Location and service area. Job posting is limited to Barangay Santa Ana, Pateros. If you use Current Location, SkillMatch reads your device location at that moment, checks whether the pin is inside the service area, and may fill the address field. SkillMatch does not continuously track you and does not use background location tracking. Matching uses stored barangay and city, not GPS coordinates. Before a Worker accepts, SkillMatch shows an approximate job area, not the exact Client pin. After a booking is confirmed, the assigned Worker and the Client may see the authorized exact job location.',
  "Ratings and reports. After a completed booking, the Client may rate the Worker. Ratings can affect a Worker's match ranking. A Worker does not rate a Client in the current version. Users may report problems through the app. Reports may be reviewed by an Administrator.",
  'Availability of the service. SkillMatch is an academic capstone platform. Features, uptime, and availability are not guaranteed. Some demonstration features, including QR Ph, run in test mode. SkillMatch may change, pause, or limit the service as the project requires.',
  'Account restrictions and administration. Authorized Administrators may review Worker identity submissions and user reports. SkillMatch may deactivate or restrict accounts. Administrators are not created through ordinary registration.',
  'Changes to these Terms. SkillMatch may update these Terms. The version identifier is 2026-09-v1. If a new version is issued, SkillMatch may ask you to review and accept it before you continue. Continued use after you accept a new version means you agree to that version.',
  'Contact. For questions about SkillMatch, contact the SkillMatch capstone project team through Pateros Technological College.',
];

export const PRIVACY_PARAGRAPHS: readonly string[] = [
  'About this Privacy Policy. This Privacy Policy explains what information SkillMatch handles when you use the SkillMatch mobile application, why it is used, and who may see it. SkillMatch is a livelihood matching platform for the Barangay Santa Ana, Pateros capstone project. This notice describes the current system. It is not a claim of lawyer or Data Protection Officer approval.',
  'Information SkillMatch handles. Depending on how you use SkillMatch, this may include account and profile information; skills; job postings; booking information; messages; ratings; reports; portfolio content; a Worker identity-verification submission; consent records; notification and device information; and job location.',
  "Account and profile data. When you register, SkillMatch handles your full name, phone number, email address, and chosen role (Worker or Client). Authentication credentials are handled by SkillMatch's authentication service. The SkillMatch application does not store your plaintext password. SkillMatch records your service-area location as Santa Ana, Pateros for this project. It does not ask you to type barangay and city at registration. A Worker profile may also include a bio, skills, availability (Available or Busy), verification status, ratings summary, and portfolio items.",
  'Worker identity-verification data. A new or unverified Worker may submit a photo of a supported valid ID and the ID type. That submission is treated as private application data. It is stored so the Worker can see their own submission status and so an authorized Administrator can review it using a time-limited secure preview. Other users, including Clients, cannot browse identity documents. SkillMatch does not verify the ID through a government database.',
  'Job and booking data. Job posts may include required skills, description, schedule, budget, payment method, written address, and a map pin. Bookings record which Client and Worker are matched, booking status, and related schedule/payment status. After confirmation, counterparties may see the contact and job-location details the current booking rules allow.',
  'Location data. SkillMatch uses location for job/service location, service-area checking, and approximate Worker opportunity display. Matching uses stored barangay and city, not GPS coordinates. Current Location, if you tap it, uses a one-time device location reading to place a job pin and optionally fill the address. SkillMatch does not continuously track your device and does not use background location tracking. Before acceptance, Workers see an approximate area. Exact pin and street address are shown only under the current authorized booking/job rules, mainly to the Client and the assigned Worker on a confirmed booking.',
  'Messages and other content. Messages are stored for the booking they belong to. SkillMatch also stores ratings, reports, and portfolio content that you or another user submit.',
  'Payment-related information. SkillMatch stores the chosen method (Cash or QR Ph) and payment status for a booking. For QR Ph, a test-mode payment provider reference may be stored so SkillMatch can check test payment status. SkillMatch does not claim to process live production payments. Do not treat a SkillMatch QR as a real payment request.',
  'Notification and device data. SkillMatch stores in-app notifications about account and booking events. If notifications are enabled on your device, SkillMatch may store a device token so those notices can be delivered. Notification text is operational (for example, a job title and a fixed status message). It is not a full copy of your chat.',
  'Consent records. When you agree to the Terms and acknowledge this Privacy Policy, SkillMatch stores the document versions and the time you accepted them on your account. Consent is not stored in sign-in metadata.',
  'How information is used. SkillMatch uses this information to operate the platform: creating and managing accounts; role access; Worker verification; job posting; matching and ranking eligible Workers; bookings; in-app communication; payment-status workflow; notifications; security; and platform administration.',
  'Matching and automated processing. SkillMatch uses rule-based matching, not AI, to decide eligibility and to score opportunities using skill, location, and rating. Ranking helps display opportunities. It does not automatically award the job. The first valid eligible Worker acceptance wins.',
  'AI-assisted features. FAQ answers come from a local knowledge base and do not read your private records. Resume Builder uses existing Worker profile data in a template. Skill Gap compares saved skills with job requirements and may add optional AI guidance. Those tools do not decide matching or hiring. Optional AI text is not guaranteed to be correct.',
  'Who may access information. You can see your own account information. A Client and a Worker on the same confirmed booking can see the counterparty and job details allowed for that booking. An Administrator can review pending Worker identity submissions and user reports, and can perform authorized administration. SkillMatch does not make identity documents public.',
  'Service providers / infrastructure. SkillMatch is operated using technical services needed to run the app, including hosting, database, sign-in, file storage, and, for QR Ph demonstration, PayMongo in TEST mode. Technical service providers may process information as necessary to provide the services SkillMatch relies on, such as authentication, database hosting, file storage, and test-mode payment functionality.',
  'Data retention. SkillMatch does not currently define a fixed public retention period. Information is retained as needed for legitimate platform operation, booking/security records, and applicable academic or administrative requirements of the project.',
  'Security. SkillMatch uses sign-in, role-based access, and private storage for protected information such as identity documents and exact job pins. No system can promise that information is 100% secure.',
  'User choices and corrections. You can review Terms and Privacy in the app, update profile information the app lets you edit, set Worker availability, and control Current Location permission on your device. SkillMatch does not currently provide an in-app "Delete My Account" or "Download All My Data" button.',
  'Research and evaluation. Any use of SkillMatch data for research or formal evaluation must follow the separately approved research process, including the applicable participant information and consent requirements.',
  'Creating a SkillMatch account does not by itself provide consent for unrelated research participation.',
  'Changes to this Privacy Policy. SkillMatch may update this Privacy Policy. The version identifier is 2026-09-v1. If a new version is issued, SkillMatch may ask you to review and acknowledge it before you continue.',
  'Contact. For privacy or account concerns, contact the SkillMatch capstone project team through Pateros Technological College.',
];

export const TERMS_DOCUMENT: LegalDocument = {
  title: TERMS_TITLE,
  version: TERMS_VERSION,
  paragraphs: TERMS_PARAGRAPHS,
};

export const PRIVACY_DOCUMENT: LegalDocument = {
  title: PRIVACY_TITLE,
  version: PRIVACY_VERSION,
  paragraphs: PRIVACY_PARAGRAPHS,
};
